### ISSUE TITLE
Fix accordion logic

### ISSUE THREAD

**Issue by krebedev** [jonahunuafe/faq-accordion-card-main#1]
Nice job @jonahunuafe .

Here's an observation:
The code appears to work correctly, but there is a potential issue with it. The problem lies in the click event listener attached to the document. When a click event occurs anywhere on the page, it closes all open answer accordions, even if the click occurs within an already opened question area. This unintended behavior could be confusing for users.

To fix this issue, you can modify the click event listener attached to the document to exclude closing the accordion when clicking on an already opened question.

**Comment by jonahunuafe** [comment]
Thanks sir for this great observation. The code has been modified to work as intended. You can check it out. Thanks once again.
